[device]
device_id = "2560E18A-0D78-4C5B-A28B-FBAB23B62AB3"
install_id = "6191A243-E9DC-4549-B47F-15A9202080E0"
pin_hash = "7880bd7fe5dcd28637eade8b95c42961c6c5acffa946a671aa0f01ce3a3479bc"

[keys]
public_key = "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEveE25N7v/w/WExblIJ4+vbydh4WDsQmkt99XwxQ/iXkFx9XKg9d4vJCyDBpp+18fZ0ycQsAYCBtwnBoh9VMAHg=="
private_key = "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgTNHeIvoXlNMfo3Ck53KTvr0BkQ4huQ1b1sBmGo9LuhKhRANCAAS94Tbk3u//D9YTFuUgnj69vJ2HhYOxCaS331fDFD+JeQXH1cqD13i8kLIMGmn7Xx9nTJxCwBgIG3CcGiH1UwAe"

# [session]
# x509 = "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEfQWeFzj7T2MGNB2GtimPyJU+04CU1vY75iU2RtvbgV+kUVAoAGYEx3gqtfQZox/sdKK6dp5EN9nwwkF1s0/ujg=="
# token_sn = "f02af5f8-59ea-4784-9295-293088819779"
# user_id_hash = "3055903"
